MusicWebApp/Models/Album.cs
namespace MusicWebApp.Models
{
    public class ServiceEndpointOptions
    {
        public ApiEndpoint[] ApiEndpoints { get; set; } = Array.Empty<ApiEndpoint>();
    }

    public class ApiEndpoint
    {
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

MusicWebApp/Models/ErrorViewModel.cs
namespace MusicWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MusicWebApp/Controllers/AlbumsController.cs
using Album.BusinessLogic.IAlbum;
using Album.BusinessLogic.Model;
using Microsoft.AspNetCore.Mvc;



namespace MusicWebApp.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly IAlbumBL _aBL;
        public AlbumsController(IAlbumBL aBL)
        {
            _aBL = aBL;
        }

        // Display Albums List
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            //For UI Testing
            //AlbumDto albumDto = new AlbumDto();

            //albumDto.AlbumId = 1;
            //albumDto.AlbumName = "TestAlbum";
            //albumDto.TrackName = "Test Track";
            //albumDto.IsChecked = false;
            //List<AlbumDto> albums = new List<AlbumDto>();

            //albums.Add(albumDto);
            //return View(albums);
            return View(await _aBL.GetAllAlbums(cancellationToken));
        }

        // Show Album Edit
        public IActionResult UpdateAlbumData(int albumid, string albumName)
        {
            var data = new AlbumDto();
            data.AlbumName = albumName;
            data.AlbumId = albumid;
            return View("Update", data);
        }

        // Update Album Data
        [HttpPost]
        public async Task<IActionResult> UpdateAlbum(AlbumDto albumDto, CancellationToken cancellationToken)
        {
            var result = await _aBL.UpdateAlbum(albumDto, cancellationToken);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View("Update", albumDto);
        }
        public async Task<IActionResult> TracksAlbum(List<AlbumDto> albums, CancellationToken cancellationToken)
        {
            var AlbumIds = (from item in albums where item.IsChecked == 
                            true select new AlbumDto() { AlbumId = item.AlbumId }).ToList();

            var result = await _aBL.GetAlbumTrackList(AlbumIds, cancellationToken);

            //For UI Testing
            //List<AlbumDto> albumsTest = new List<AlbumDto>();
            //AlbumDto albumDto = new AlbumDto();

            //albumDto.AlbumId = 1;
            //albumDto.AlbumName = "TestAlbum2";
            //albumDto.TrackName = "Test Track2";
            //albumDto.IsChecked = false;
            //albumsTest.Add(albumDto);

            //AlbumDto albumDto2 = new AlbumDto();
            //albumDto2.AlbumId = 2;
            //albumDto2.AlbumName = "TestAlbum3";
            //albumDto2.TrackName = "Test Track3";
            //albumDto2.IsChecked = false;
            //albumsTest.Add(albumDto2);



            //List<AlbumDto> result = albumsTest;
            //List<AlbumDto> result = albums;

            if (result != null)
            {
                return View("Tracks", result);
            }

            return base.View("Tracks", new AlbumDto());


        }

    }
}

MusicWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MusicWebApp.Models;
using System.Diagnostics;

namespace MusicWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MusicWebApp/Views/Albums/Index.cshtml
@model List<Album.BusinessLogic.Model.AlbumDto>

@{
    ViewData["Title"] = "Home Page";
}


@using (Html.BeginForm("TracksAlbum", "Albums", FormMethod.Post))
{
    <div class="container">
        <div class="col-md-12">
            <div>
                <h2 class="centreContent">Album List Table</h2>
            </div>

            <div class="row">
                <br />
                <div style="height:200px;overflow-y:hidden">
                    <table class="table table-bordered">
                        <tr>
                            <th>Album Id</th>
                            <th>
                                Album Name
                            </th>
                            <th>Select</th>
                        </tr>

                        @for (var i = 0; i < Model.Count(); i++)
                        {
                            <tr>
                                <td>                                    
                                    @Html.DisplayFor(m => Model[i].AlbumId)
                                </td>
                                <td>
                                    @Html.ActionLink(Model[i].AlbumName
                                                    ,"UpdateAlbumData"
                                                    ,"Albums"
                                                    ,new {albumid = Model[i].AlbumId,albumName=Model[i].AlbumName },null)
                                </td>
                                <td>
                                    @Html.HiddenFor(m => Model[i].AlbumId)
                                    @Html.CheckBoxFor(m=> Model[i].IsChecked)
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="submit" class="btn btn-warning">View Selected TrackList</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    

</script>

MusicWebApp/Views/Albums/Tracks.cshtml
@model IEnumerable<Album.BusinessLogic.Model.AlbumDto>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">

    <div class="col-md-8">
        <div class="col-6">
            <h2 class="text-info">Track List</h2>
        </div>
        <div class="row">
            <br />
            <div>
                <table class="table">
                    <tr>
                        <th>Album Id</th>
                        <th>
                            Album Name
                        </th>
                        <th>Track Name</th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.AlbumId)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.AlbumName)                              
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.TrackName)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>

    </div>
</div>

MusicWebApp/Views/Albums/Update.cshtml
@model Album.BusinessLogic.Model.AlbumDto
@{
    ViewData["Title"] = "Home Page";
}

@using (Html.BeginForm("UpdateAlbum", "Albums", FormMethod.Post))
{
    <div class="form-horizontal">

        <h2 class="text-info">Update Album</h2>

        <div class="form-group">

            @Html.LabelFor(model =>Model.AlbumName, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model=>Model.AlbumName, new { @class="form-control"})
            </div>
            @Html.HiddenFor(model=>Model.AlbumId)
        </div>

        <br/>
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" value="Update" class="btn btn-primary">Update Album Details</button>
            
        </div>

    </div>
}

MusicWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MusicWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <style>
        .centreContent{
            text-align: center;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MusicWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>